books_app/urls.py
from django.conf.urls import url
from django.urls import include, re_path
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
import books_app.views as views
from books_app.views.model_views import books as BookViews
from books_app.views.model_views import owners as OwnerViews
from books_app.views.model_views import texts as TextViews



urlpatterns = [
    path("", views.index, name="index"),
    path("loadup/", views.loadup, name="loadup"),
    # Django will expect a string and send it to the view as var owner_id
    path("books/<str:book_id>", BookViews.books, name="books"),
    path("owners/<str:owner_id>/", OwnerViews.owners, name="owners"),
    path("texts/<str:text_id>/", TextViews.texts, name="texts"),
    path(
        "books-shelfmark-autocomplete/",
        BookViews.books_shelfmark_autocomplete,
        name="books-shelfmark-autocomplete",
    ),
    path(
        "books-author-autocomplete/",
        BookViews.books_author_autocomplete,
        name="books-author-autocomplete",
    ),
    path(
        "books-tag-autocomplete/",
        BookViews.books_tag_autocomplete,
        name="books-tag-autocomplete",
    ),
    path(
        "books-text-autocomplete/",
        BookViews.books_text_autocomplete,
        name="books-text-autocomplete",
    ),
    path(
        "books-language-autocomplete/",
        BookViews.books_language_autocomplete,
        name="books-language-autocomplete",
    ),
    path(
        "owners-name-autocomplete/",
        OwnerViews.owners_name_autocomplete,
        name="owners-name-autocomplete",
    ),
    path("search", views.search, name="search"),
    path("about", views.about, name="about"),
    path("suggest", views.suggest_sel, name="suggest_sel"),
    path("suggest/book", BookViews.suggest_book, name="suggest_book"),
    path("suggest/owner", OwnerViews.suggest_owner, name="suggest_owner"),
    path("teach", views.teach, name="teach"),
    path("bibliography", views.bibliography, name="bibliography"),
    #    url(r'^captcha/', include('captcha.urls')),
]

books_app/models.py
from django.contrib.gis.db import models
from django.forms import ModelForm
import datetime

    
UNIVERSAL_DATE_RANGE = [
    datetime.datetime(1300, 1, 1),
    datetime.datetime(1600, 1, 1),
]

def date_ranges(given_dates):
    from datetime import datetime, timedelta
    # Split on the dash into two dates
    if given_dates.find("post-") != -1:
        given_dates = given_dates.replace("post-", "post")
    if given_dates.find("pre-") != -1:
        given_dates = given_dates.replace("pre-", "pre")
    if given_dates.find("s") != -1:
        given_dates = given_dates.replace("s","")
    dates = given_dates.split("-")
    # Defaults
    month = "January"
    day = 1
    year = 1300
    final = []
    chop = 0
    firstDate = True
    if len(dates[0]) == 0 and len(dates[1]) == 0:
        return UNIVERSAL_DATE_RANGE
    # For start date and finish date
    for date in dates:
        # Take off white space
        uncertain = False
        date = date.lstrip()
        date = date.rstrip()
        # How we want to organize uncertain dates
        if (date.find("?") != -1 and len(date) < 2) or date.find("???") != -1:
            # When we get just a "?"
            if firstDate:
                date = "1300"
            else:
                date = "1600"
        if date.find("?") != -1 and date.find("??") == -1:
            # Maybe add an uncertainty factor to this
            # If we get a date with a ? i.e. "1460?"
            date = date.replace("?", "")
            uncertain = True
        if date.find("post") != -1:
            if firstDate:
                date = date.replace("post", "")
            else:
                date = "1500"
        if date.find("pre") != -1:
            if firstDate:
                date = "1350"
            else:
                date = date.replace("pre", "")
        if date.find("??") != -1:
            if firstDate:
                date = date.replace("??", "00")
            else:
                date = date.replace("??", "99")
        if "c." in date:
            # 'c. 1450'
            # Maybe do a +/- operation to just get a range straight off the bat
            # For now just get rid of the c.
            date = date.replace("c. ", "")
            date = date.replace("c.", "")
        if date.find("/") != -1:
            chop = date.index("/")
            if firstDate:
                # Take the earlier date- this is most/all of the dates we encounter
                date = date[:chop]
            else:
                # Take the later date when its the second date- widest range
                # (Makes "1450/60 "into "1460")
                # date = date[:chop-2]+date[chop+1:]
                date = date[chop + 1 :]
        # We now have a certain date (no c., ?, /, etc.) we can format it for datetime
        date = date.split(" ")
        if len(date[0]) < 3:
            # e.g. 15 December 1443
            day = date[0]
            month = date[1]
            year = date[2]
        elif len(date) == 2:
            # e.g. December 1443
            month = date[0]
            year = date[1]
        else:
            # Some stuff going on here with spaces/tabs
            if len(date[0]) == 3 and firstDate:
                date[0] = date[0] + "" + "0"
            if len(date[0]) == 3 and not firstDate:
                date[0] = date[0] + "" + "9"
            # e.g. 1443
            year = date[0]
        stringIt = str(year) + "-" + month + "-" + str(day)
        try:
            # format for adding a datetime from a string
            toAdd = datetime.strptime(stringIt.replace("pot", "").replace("Augut", "August"), "%Y-%B-%d")
            if uncertain and firstDate:
                toAdd = toAdd - timedelta(days=1826)
            if uncertain and not firstDate:
                toAdd = toAdd + timedelta(days=1824)
            final.append(toAdd)
            firstDate = False
        except ValueError:
            return UNIVERSAL_DATE_RANGE
    # If there is no dash we extend the window to a whole year
    if len(final) == 1:
        final.append(final[0] + timedelta(days=364))
    return final


class Book(models.Model):
    image = models.ImageField(null=True, blank=True)
    shelfmark = models.CharField(max_length=200)
    about = models.TextField(blank=True, verbose_name="About/Content")
    text = models.ManyToManyField("Text", blank=True, verbose_name="Text(s)")

    type_print = "Print"
    Manuscript = "Manuscript"
    type_choices = [(type_print, "Print"), (Manuscript, "Manuscript")]
    type = models.CharField(max_length=30, choices=type_choices, default="Manuscript")

    ex_libris = models.TextField(
        blank=True
    )  # Hasn't been used yet, but is in AirTable so leaving it here
    date_created = models.CharField(max_length=200, blank=True, null=True)
    catalog_entry = models.CharField(max_length=2000, blank=True)
    digital_version = models.CharField(max_length=200, blank=True)
    format = models.TextField("Form/Format", blank=True)
    scribes = models.ManyToManyField("Scribe", blank=True)
    illuminators = models.ManyToManyField("Illuminator", blank=True)
    printer = models.ManyToManyField(
        "Printer", blank=True, verbose_name="Printer Information"
    )
    # These fields are important for mapping
    book_location = models.ManyToManyField(
        "BookLocation", blank=True
    )  # These are searched in the map
    # Helps us cross reference book ownership, also convenient to display on templates
    owner_info = models.ManyToManyField(
        "DateOwned", blank=True, verbose_name="Ownership Information/History"
    )
    bibliography = models.ManyToManyField("Bibliography", blank=True)
    reviewed = models.BooleanField(null=True, default=False)
    comments = models.TextField(blank=True, verbose_name="User Suggestion Comments")
    editor_credit = models.TextField(blank=True, verbose_name="Editor Credit")

    def __str__(self):
        return self.shelfmark


class Owner(models.Model):
    image = models.ImageField(null=True, blank=True)
    image_citation = models.CharField(max_length=500, blank=True, null=True)
    bio = models.URLField(null=True, blank=True, max_length=500)
    name = models.CharField(max_length=200)
    titles = models.CharField(max_length=200, blank=True, null=True)
    birth_year = models.CharField(max_length=200, blank=True, null=True)
    death_year = models.CharField(max_length=200, blank=True, null=True)

    Female = "Female"
    Male = "Male"
    gen_choices = [(Female, "Female"), (Male, "Male")]
    gender = models.CharField(max_length=9, choices=gen_choices, default="Female")

    motto = models.CharField(max_length=200, blank=True, null=True)
    symbol = models.CharField("Symbol(s)", max_length=200, blank=True, null=True)

    arms = models.ImageField(null=True, blank=True)
    arms_citation = models.CharField(max_length=500, blank=True, null=True)
    signatures = models.ImageField(null=True, blank=True)
    signatures_citation = models.CharField(max_length=500, blank=True, null=True)

    # Helps us cross refernce and useful in templates
    book_date = models.ManyToManyField(
        "DateOwned", blank=True, verbose_name="Instance of Book Ownership"
    )
    # This is the object we search for the map- a date range where an owner was in a location
    owner_location = models.ManyToManyField("OwnerPlaceDateLived", blank=True)
    relation = models.ManyToManyField("Relative", blank=True, verbose_name="Relatives")
    reviewed = models.BooleanField(null=True, default=False)
    comments = models.TextField(blank=True, verbose_name="User Suggestion Comments")
    editor_credit = models.TextField(blank=True, verbose_name="Editor Credit")

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def name_abbr(self):
        comma = self.name.find(",")
        if comma != -1:
            return self.name[0:comma]
        else:
            return self.name


# A text can appear in multiple books and a book can have multiple texts, this mostly helps fill out the template
class Text(models.Model):
	title = models.CharField(max_length=200)
	name_eng = models.CharField(max_length=200, blank=True)
	tags = models.ManyToManyField('Tag', blank=True)
	language = models.ManyToManyField('BooksLanguage', blank=True)
	date_composed = models.CharField(max_length=200, blank=True, verbose_name="Date Composed (if known)")
	#author = models.ForeignKey('Author', on_delete=models.CASCADE, blank=True, null=True, related_name='old_author')
	authors = models.ManyToManyField('Author', blank=True)
	#translator = models.ForeignKey('Translator', on_delete=models.CASCADE, blank=True, null=True, related_name='old_translator')
	translators = models.ManyToManyField('Translator', blank=True)
	parent_text = models.ManyToManyField('Text', blank=True)
	arlima_link = models.CharField(max_length=200, blank=True)
	me_compendium_link = models.CharField(max_length=200, blank=True, verbose_name="ME Compendium Link")
	ihrt_link = models.CharField(max_length=800, blank=True)
	estc_link = models.CharField(max_length=800, blank=True, verbose_name="ESTC Link")
	ustc_link = models.CharField(max_length=800, blank=True, verbose_name="USTC Link")
	hsc_link = models.CharField(max_length=800, blank=True, verbose_name="HSC link")
	gw_link = models.CharField(max_length=800, blank=True, verbose_name="GW link")
	vd16_link = models.CharField(max_length=800, blank=True, verbose_name="VD16 link")
	fama_link = models.CharField(max_length=800, blank=True, verbose_name="FAMA link")

	def __str__(self):
		return self.title

# These are the owner related objects we map- first we will find the owners which fit a search criteria in the view,
# then we decide which of these to send to the template based on their date_range()
class OwnerPlaceDateLived(models.Model):
    # This is the field leaflet uses to put pins on the map
    geom = models.PointField(null=True, blank=True)

books_app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<title>Books of Duchesses</title>

<head>
<link rel="shortcut icon" type="image/png" href="https://lh3.googleusercontent.com/proxy/ropw1-qPxCyit3DtxuQtWmoUHPC7HC9FikXUnr_IdMZRzdA5srDWrGbIRlr1lL8CmP2u2CLMCK2RjokQy6ktHSSjpotjcPNticEshujjtxSeOadImA"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144638211-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-144638211-1');
</script>
</head>

<!-- Meta and stylesheets -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Shuffle/5.2.2/shuffle.js"></script>
<!-- Leaflet references -->
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js" integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==" crossorigin=""></script>

<body>
<div class="container" style="overflow:hidden; display:block; position:relative; padding-bottom:125px;">
  <!-- Navbar (sit on top) -->
  <div class="w3-top">
    <div class="w3-bar w3-white w3-wide w3-padding w3-card">
      <a href="/" class="w3-bar-item w3-button">Books of Duchesses</a>
      <!-- Float links to the right. Hide them on small screens -->
      <div class="w3-right w3-hide-small">
        <a href="/about" class="w3-bar-item w3-button">About/Usage</a>
        <a href="./#map" class="w3-bar-item w3-button">Map</a>
        <a href="/search" class="w3-bar-item w3-button">Search</a>
	<a href="/suggest" class="w3-bar-item w3-button">Suggest</a>
  <a href="/teach" class="w3-bar-item w3-button">Teach</a>
	<a href="/bibliography" class="w3-bar-item w3-button">Bibliography</a>
       <!-- <a href="https://booksofduchesses.com/howto" class="w3-bar-item w3-button">How To Use</a> -->
       <!-- <a href="#owners" class="w3-bar-item w3-button">Books & Book Owners</a> -->
      </div>
    </div>
  </div>

  <!-- Page content here -->
  {% block content %}{% endblock %}
  <!-- End page content -->

  <!-- Footer -->
  <div style="width:100%; text-align:center;">
    <footer style="width:100%; position:absolute; bottom:0; padding-bottom:0px; background:#add8e6;">
      <p><a href="https://www.haverford.edu"><strong>Haverford College</strong></a></p>
      <p style="font-size: 13px;">&copy; <a href="https://www.haverford.edu/library/digital-scholarship">2020 Haverford College Libraries</a></p>
    </footer>
  </div>
</div>

</body>
</html>

books_app/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<title>Books of Duchesses</title>
<link rel="shortcut icon" type="image/png" href="https://lh3.googleusercontent.com/proxy/ropw1-qPxCyit3DtxuQtWmoUHPC7HC9FikXUnr_IdMZRzdA5srDWrGbIRlr1lL8CmP2u2CLMCK2RjokQy6ktHSSjpotjcPNticEshujjtxSeOadImA"/>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144638211-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-144638211-1');
</script>
</head>
<div class="everything">
  <div class="w3-top">
    <div class="w3-bar w3-white w3-wide w3-padding w3-card">
      <a href="/" class="w3-bar-item w3-button">Books of Duchesses</a>
      <!-- Float links to the right. Hide them on small screens -->
      <div class="w3-right w3-hide-small">
        <a href="/about" class="w3-bar-item w3-button">About/Usage</a>
        <a href="./#map" class="w3-bar-item w3-button">Map</a>
        <a href="/search" class="w3-bar-item w3-button">Search</a>
	<a href="/suggest" class="w3-bar-item w3-button">Suggest</a>
	<a href="/bibliography" class="w3-bar-item w3-button">Bibliography</a>
       <!-- <a href="#owners" class="w3-bar-item w3-button">Books & Book Owners</a> -->
      </div>
    </div>
  </div>
{% block content %}{% endblock %}
<!-- No footer w/ bootstrap stylesheet  -->

</div>
</html>

books_app/templates/footer.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<footer>
  <a href="https://www.haverford.edu/" style="color: #A20000"><strong>Haverford College</strong></a>
  <!-- Add font awesome icons -->
  <a href="https://www.facebook.com/hclibraries/" class="fa fa-facebook"></a>
  <a href="https://twitter.com/hclibraries?lang=en" class="fa fa-twitter"></a>
  <a href="https://www.instagram.com/hclibraries/" class="fa fa-instagram"></a>
  <br>
  <br>
  <a href="https://www.rice.edu/" style="color: #00205B;"><strong>Rice University</strong></a>
  <!-- Add font awesome icons -->
  <a href="https://www.facebook.com/hclibraries/" class="fa fa-facebook"></a>
  <a href="https://twitter.com/hclibraries?lang=en" class="fa fa-twitter"></a>
  <a href="https://www.instagram.com/hclibraries/" class="fa fa-instagram"></a> 
  <br style="line-height: 10px;">
  <!-- <p style="font-size: 13px; text-align: center;"><strong>&copy; 2019 Haverford College Libraries</strong></p> -->


</footer>

books_app/templates/navbar.html
{% extends "base.html" %}

{% load staticfiles %}
{% block navbar %}

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
    <a href="#home" class="w3-bar-item w3-button"><b>BR</b> Architects</a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="#projects" class="w3-bar-item w3-button">Projects</a>
      <a href="#about" class="w3-bar-item w3-button">About</a>
      <a href="#contact" class="w3-bar-item w3-button">Contact</a>
    </div>
  </div>
</div>

{% endblock%}

books_app/templates/texts.html
{% extends "base.html" %}
{% load staticfiles %}
{% load geojson_tags %}

{% block content %}
<!-- Leaflet style -->
<script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css">

 <!-- Load Esri Leaflet from CDN -->
  <script src="https://unpkg.com/esri-leaflet@2.5.3/dist/esri-leaflet.js"
    integrity="sha512-K0Vddb4QdnVOAuPJBHkgrua+/A9Moyv8AQEWi0xndQ+fqbRfAFd47z4A9u1AW/spLO0gEaiE1z98PK1gl5mC5Q=="
    crossorigin=""></script>

<!-- Page container -->
<div class="column-left">

  <div class="w3-container w3-padding-32" id="about">
    <h2 style="text-align:center; padding-top:30px;">Text: {{ text.title }}</h2>
    {% if text.name_eng %}
      <h3 class="w3-opacity" style="text-align:center;">{{ text.name_eng }}</h3>
    {% endif %}
    <hr></hr>
  </div>
<!-- Left Column, basic information -->
  <div style="padding-left:20px; text-align:center; padding-right:0px;">
    <div class="w3-col l3 m6 w3-margin-bottom">
      <h3 style="text-align:center;"><strong>Overview</strong></h3>
      <h4 class="w3-opacity">Found in:</h4>
      <ul>
      {% for book in books %}
        <li style="list-style-position: inside"> <a href="http://booksofduchesses.com/books/{{book.shelfmark}}">{{book.shelfmark}}</a></li>
      {% endfor %}
      </ul> 
      <hr></hr>
      {% if text.date_composed %}
        <p class="w3-opacity">Created in {{text.date_composed}}</p>
      {% endif %}
      {% for language in languages %}
        <p>{{language.books_language}}</p>
      {% endfor %}
      <!-- We need a case for a text without authors -->
      {% if authors %}
        {% for author in authors %}
  	      {% if author.link %}
  	        <p>Author: <a style="color:blue;" href="{{author.link}}"> {{author.name}}</a></p>
  	      {% else %}
                <p>Author: {{author.name}}</p>
  	      {% endif %}
        {% endfor %}
      {% else %}
        <p>Author Unknown</p>
      {% endif %}
      {% if translators %}
        {% for translator in translators %}
              {% if translator.link %}
                <p>Translator: <a style="color:blue;" href="{{translator.link}}">{{translator}}</a></p>
              {% else %}
                <p>Translator: {{translator}}</p>
              {% endif %}
        {% endfor %}
      {% else %}
        <p>Translator Unknown</p>
      {% endif %}
      <hr></hr>
      {% if text.parent_text.all %}
      <h4 class="w3-opacity">Parent Texts:</h4>
      <ul>
        {% for text in text.parent_text.all %}
        <li style="list-style-position: inside"><a href="https://booksofduchesses.com/texts/{{text.title}}">{{text.title}}</a></li>
        {% endfor %}
      </ul>
      {% endif%}

      {% if text.text_set.all %}
      <h4 class="w3-opacity">Child Texts:</h4>
      <ul>
        {% for text in text.text_set.all %}
        <li style="list-style-position: inside"><a href="https://booksofduchesses.com/texts/{{text.title}}">{{text.title}}</a></li>
        {% endfor %}
      </ul>
      {% endif%}

      {% if tags %}
        <h4 class="w3-opacity">Tags:</h4>
      {% else %}
        <p class="w3-opacity">Tags: None</p>
      {% endif %}
      <ul>
      {% for tag in tags %}
        <li style="list-style-position: inside">{{tag}}</li>
      {% endfor %}
      </ul>
    </div>

    <!-- Map -->
    <div id="mapid" style="width:42%; height:600px; left:40px; float:left; z-index:0;">
      <script>

        var greenIcon = new L.Icon({
            iconUrl: 'https://cdn.rawgit.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png',
          	shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
          	iconSize: [25, 41],
          	iconAnchor: [12, 41],
          	popupAnchor: [1, -34],
            shadowSize: [41, 41]
        });

        var mymap = L.map('mapid').setView([50.332721, 1.050860], 5);

        //L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        //        maxZoom: 18,
        //        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
        //                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
        //                'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        //        id: 'mapbox.streets'
        //}).addTo(mymap);
	L.esri.basemapLayer('Topographic').addTo(mymap);


        var places = {{ places|geojsonfeature:'popupcontent'|safe }};
        var mcg = new L.MarkerClusterGroup();

        var bookLayer = L.geoJSON(places, {
            pointToLayer: function (feature, latlng) {
                  return L.marker(latlng, {icon: greenIcon});
        },

        onEachFeature: function(feature, layer) {
            var props = feature.properties.popupcontent;
            var content = `<p>${props}</p>`;
            layer.bindPopup(content);
        }
        });
        mcg.addLayer(bookLayer);
        mymap.addLayer(mcg);

      </script>
    </div>
    <!-- Right column -->
    <div class="w3-col l3 m6 w3-margin-bottom" style="padding-right: 10px; width: 28%; float:right; text-align:center;">
      <h3 style="text-align:center;"><strong>Ownership Details</strong></h3>
<!--
      {% for date in dates %}
	{% if date.book_owner.gender == "Male" %}
          <p style="font-size:13px;"><a style="color: blue;" href="https://booksofduchesses.com/books/{{date.book_owned}}">{{date.book_owned}}</a> owned by {{date.book_owner}} ({{date.dateowned}})
          ownership {{date.conf_or_possible}} with {{date.evidence}} as evidence.</p>
        {% else %}
          <p style="font-size:13px;"><a style="color: blue;" href="https://booksofduchesses.com/books/{{date.book_owned}}">{{date.book_owned}}</a> owned by <a style="color: blue;" href="https://booksofduchesses.com/owners/{{date.book_owner}}">{{date.book_owner}}</a> ({{date.dateowned}})
	   ownership {{date.conf_or_possible}} with {{date.evidence}} as evidence.</p>
	{% endif %} 
     {% endfor %}
-->
      {% for date in books_list %}
	{% if date.0.book_owner.gender == "Male" %}
          <p style="font-size:13px;"><a style="color: blue;" href="https://booksofduchesses.com/books/{{date.0.book_owned}}">{{date.0.book_owned}}</a> owned by {{date.0.book_owner}} ({{date.0.dateowned}}).
          {% for a in date.1 %}  
            Ownership {{a.conf_or_possible}} with {{a.evidence}} as evidence.
       	  {% endfor %}
	    </p>
        {% else %}
           <p style="font-size:13px;"><a style="color: blue;" href="https://booksofduchesses.com/books/{{date.0.book_owned}}">{{date.0.book_owned}}</a> owned by <a style="color: blue;" href="https://booksofduchesses.com/owners/{{date.0.book_owner}}">{{date.0.book_owner}}</a> ({{date.0.dateowned}}).
          {% for a in date.1 %}
	   Ownership {{a.conf_or_possible}} with {{a.evidence}} as evidence.
	  {% endfor %}
	    </p> 
	{% endif %} 
     {% endfor %}

      <br></br>
      <h3 style="text-align:center;"><strong>Bibliography</strong></h3>
      {% if text.arlima_link %}
      <p><a style="color: blue;" href="{{text.arlima_link}}">Arlima</a></p>
      {% endif %}
      {% if text.me_compendium_link %}
       <p><a style="color: blue;" href="{{text.me_compendium_link}}">ME Compendium</a></p>
      {% endif %}
      {% if text.ihrt_link %}
        <p><a style="color: blue;" href="{{text.ihrt_link}}">IHRT</a></p>
      {% endif %}
      {% if text.estc_link %}
        <p><a style="color: blue;" href="{{text.estc_link}}">ESTC</a></p>
      {% endif %}
      {% if text.ustc_link %}
        <p><a style="color: blue;" href="{{text.ustc_link}}">USTC</a></p>
      {% endif %}
      <hr></hr>
    </div>  
  </div>

</div>
{% endblock %}